User auth
GregoryNavasarkian/software-programming-quiz pull request #18
Opened 2023-04-19 10:17 UTC by GregoryNavasarkian

I set up the auth for the backend. 

I also set up nodemailer for the password reset using an email I created (softwareprogrammingquiz@proton.me) and a service called *SendGrid*. I did it in a way that the sendEmail function in the utils folder can be used in multiple ways (since we will need it later). 

I tested it all with postman, and it all works. Surprisingly 😂

I didn't set up the linking to quizzes for each employer, as that would require setting up some more models, etc.

2023-04-20 02:46 UTC, Schnaidm requested changes
looks great but I'm just wondering if it makes sense that we used two different packages to send email s - you used nodemailer and I used emailjs.

Do you think we should change one of them so they both match?

2023-04-20 03:20 UTC, GregoryNavasarkian commented
Sadly there is no other way since the password reset requires a token to be created and added to the employer entry in the database. That is how it is checked to make sure the reset is not just some random person.

2023-04-20 03:20 UTC, GregoryNavasarkian commented
The frontend cant create a reset token

2023-04-21 13:03 UTC, Schnaidm approved these changes

2023-04-21 22:07 UTC, merged